Implemented UpdateFields task for Jira. Added OAuth authorization
kestra-io/plugin-jira pull request #11
Opened 2024-08-14 16:08 UTC by iNikitaGricenko

### What changes are being made and why?

- Implemented task to update fields in Jira ticket (#10)
- Added OAuth authorization using accessToken
---

### How the changes have been QAed?

```yaml
id: jira_update_field
namespace: company.myteam
tasks:
  - id: update_ticket_field
    type: io.kestra.plugin.jira.issues.UpdateFields
    baseUrl: your-domain.atlassian.net
    accessToken: "{{ secret('my_jira_access_token') }}"
    issueIdOrKey: YOUR_ISSUE_KEY
    fields:
      description: "Updated description of: {{ execution.id }}"
      customfield_10005: "Updated value"
```

---

2024-08-14 16:28 UTC, loicmathieu requested changes

2024-08-14 16:28 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/jira/issues/JiraClient.java
> +    protected String passwordOrToken;
Thsi plugin has already been published in 0.18 so you cannot change a property name for backward compatibility

2024-08-14 16:28 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/jira/issues/UpdateFields.java
> +    title = "Update a Jira field",
```suggestion
    title = "Update Jira fields",
```

2024-08-14 16:28 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/jira/issues/UpdateFields.java
> +    description = "Updates a specific field in a Jira ticket."
```suggestion
    description = "Update specific fields in a Jira ticket."
```

2024-08-14 16:28 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/jira/issues/UpdateFields.java
> +            title = "Update a Jira ticket field",
```suggestion
            title = "Update a Jira ticket fields",
```

2024-08-15 15:47 UTC, anna-geller commented
closes https://github.com/kestra-io/plugin-jira/issues/10

2024-08-16 07:37 UTC, loicmathieu approved these changes
LGTM

2024-08-16 07:42 UTC, merged