feat(plugin): supports issuetype field for jira-plugin in kestra
kestra-io/plugin-jira pull request #14
Opened 2024-10-23 12:19 UTC by MustafaMunir123

make isssuetype field dynamic

set  `Task` as default issue type (as it is supported in the lowest subscription plan of jira unlike `Story`)

close #12

### What changes are being made and why?
- Add issuetype field for jira-plugin
- Modify examples accordingly
- Set `Task` as default
---

### How the changes have been QAed?

```yaml
id: jira_flow
namespace: company.myteam

tasks:
  - id: create_issue
    type: io.kestra.plugin.jira.issues.Create
    baseUrl: your-domain.atlassian.net
    username: your_email@example.com
    password: "{{ secret('your_jira_api_token') }}"
    projectKey: myproject
    summary: "Workflow failed"
    description: "{{ execution.id }} has failed on {{ taskrun.startDate }} See the link below for more details"
    labels:
      - bug
      - workflow
    issueType: "Story"  # default --> "Task"
```

2024-10-24 03:07 UTC, MustafaMunir123 commented
@Ben8t this PR is Ready for Review

2024-10-24 10:22 UTC, aaliyan1230 commented
@Ben8t hey i was thinking if we can have this PR merged at your earliest convenience as I need this feature as part of jira plugin for my project using kestra, right now I have hackily customized the org plugin.

2024-10-24 10:30 UTC, Ben8t commented
Hey @MustafaMunir123 thanks for the PR

@mgabelle can you review it please 🙏

2024-10-24 13:19 UTC, mgabelle requested changes

2024-10-24 14:24 UTC, mgabelle commented on src/main/java/io/kestra/plugin/jira/issues/JiraTemplate.java
> +                "issuetype", runContext.render(issuetype)
OK, thank you for pointing this out. Then let's keep it lowercase.

2024-10-25 03:11 UTC, MustafaMunir123 commented on src/main/resources/jira-template.peb
> +            "name": "{{issuetype}}"
Done

2024-10-25 03:11 UTC, MustafaMunir123 commented on src/main/java/io/kestra/plugin/jira/issues/JiraTemplate.java
> +            issuetype = runContext.render(issuetype) == null ? "Task" : runContext.render(issuetype);
Done

2024-10-25 03:11 UTC, MustafaMunir123 commented on src/main/java/io/kestra/plugin/jira/issues/JiraTemplate.java
> +    protected String issuetype;
Done

2024-10-25 06:44 UTC, mgabelle approved these changes

2024-10-25 06:44 UTC, merged

2024-10-25 06:45 UTC, mgabelle commented
PR merged, thank you @MustafaMunir123 .